import type { StaticClause } from "@/components/layouts/StaticArticle";
import { EditorialP, MailA } from "@/components/layouts/editorial";

/**
 * /about — content clauses
 * ────────────────────────
 * Wave 3N (personas 94, 95): ships the "About AlphaDesk" page that first-
 * time visitors were asking for — what the product is, who runs it, the
 * jurisdiction, and a plain non-broker-dealer disclaimer. Kept in the same
 * `StaticClause` shape /terms and /privacy use so the editorial column
 * styling is identical to the other marketing surfaces.
 *
 * Intentionally honest. No fabricated team info, no headcount numbers,
 * no pretend investor names.
 */
export const ABOUT_CLAUSES: StaticClause[] = [
  {
    index: "01",
    title: "What AlphaDesk is",
    body: (
      <EditorialP>
        AlphaDesk is an AI-powered trading terminal that combines a
        systematic strategy library, real-time market analysis, and an
        AI-authored research layer in a single desk. It is a software
        tool that connects to your brokerage account (currently Alpaca
        Markets) and your AI provider (currently Anthropic Claude) — we route your
        orders to your broker and your prompts to your model. We do not
        hold client funds and we do not take custody of your account.
      </EditorialP>
    ),
  },
  {
    index: "02",
    title: "Who runs it",
    body: (
      <>
        <EditorialP>
          AlphaDesk is built by AlphaDesk Labs, a small founder-led team.
          We are invite-only while we harden the platform and scale the
          user base deliberately. There is no sales team, no quota, and
          no paid growth.
        </EditorialP>
        <div className="mt-3">
          <EditorialP>
            If you are reading this page, you either have an invite or are
            on the waitlist — both are good places to be.
          </EditorialP>
        </div>
      </>
    ),
  },
  {
    index: "03",
    title: "Jurisdiction",
    body: (
      <EditorialP>
        AlphaDesk Labs is organized as a Delaware LLC. The terms of service
        and privacy policy are governed by the laws of the State of
        Delaware, United States. Disputes resolve through binding
        arbitration — see the{" "}
        <a
          href="/terms"
          className="text-primary underline decoration-brand-dim underline-offset-4 hover:text-gold-300"
        >
          Terms of Service
        </a>{" "}
        for the full clause.
      </EditorialP>
    ),
  },
  {
    index: "04",
    title: "Not a broker-dealer",
    body: (
      <>
        <EditorialP>
          AlphaDesk is not a registered broker-dealer, investment adviser,
          or financial institution. We do not execute your trades — Alpaca
          Markets does. We do not give investment advice — the analysis
          you see is generated by language models and the strategies are
          systematic rules that you chose to run.
        </EditorialP>
        <div className="mt-3">
          <EditorialP>
            Trading securities involves substantial risk of loss. Read the{" "}
            <a
              href="/risk"
              className="text-primary underline decoration-brand-dim underline-offset-4 hover:text-gold-300"
            >
              Risk Disclosure
            </a>{" "}
            before you connect a live account.
          </EditorialP>
        </div>
      </>
    ),
  },
  {
    index: "05",
    title: "Contact",
    body: (
      <EditorialP>
        Legal questions — <MailA address="legal@tradingalpha.net" />. Support,
        security, and press each have their own address on the{" "}
        <a
          href="/contact"
          className="text-primary underline decoration-brand-dim underline-offset-4 hover:text-gold-300"
        >
          Contact
        </a>{" "}
        page.
      </EditorialP>
    ),
  },
];
