import SwiftUI

// MARK: - View Model

@Observable
final class ReportsViewModel {
    var equity: Double = 0
    var cash: Double = 0
    var buyingPower: Double = 0
    var unrealizedPnl: Double = 0
    var unrealizedPnlPct: Double = 0
    var realizedPnlToday: Double = 0

    var positions: [Position] = []
    var closedOrders: [Order] = []
    var isLoading = true
    var error: String?

    var totalPositionValue: Double {
        positions.reduce(0) { $0 + $1.marketValue }
    }

    var totalUnrealizedPnl: Double {
        positions.reduce(0) { $0 + $1.unrealizedPnl }
    }

    var winningTrades: Int {
        closedOrders.filter { order in
            let side = order.side.lowercased()
            // Simplified: count filled sells as potential wins
            return side == "sell" && (order.status?.lowercased().contains("fill") ?? false)
        }.count
    }

    var filledOrders: [Order] {
        closedOrders.filter { ($0.status?.lowercased().contains("fill") ?? false) }
    }

    @MainActor
    func refresh() async {
        isLoading = positions.isEmpty && closedOrders.isEmpty
        error = nil

        await withTaskGroup(of: Void.self) { group in
            group.addTask { await self.fetchSummary() }
            group.addTask { await self.fetchPositions() }
            group.addTask { await self.fetchOrders() }
        }

        withAnimation(.easeInOut(duration: 0.25)) {
            isLoading = false
        }
    }

    @MainActor
    private func fetchSummary() async {
        do {
            let summary: PortfolioSummary = try await APIClient.shared.request(.portfolioSummary)
            equity = summary.equity
            cash = summary.cash
            buyingPower = summary.buyingPower
            unrealizedPnl = summary.unrealizedPnl
            unrealizedPnlPct = summary.unrealizedPnlPct
            realizedPnlToday = summary.realizedPnlToday
        } catch {
            self.error = error.localizedDescription
        }
    }

    @MainActor
    private func fetchPositions() async {
        do {
            positions = try await APIClient.shared.request(.positions)
        } catch {
            // Non-fatal
        }
    }

    @MainActor
    private func fetchOrders() async {
        do {
            let orders: [Order] = try await APIClient.shared.request(.orders)
            closedOrders = orders
        } catch {
            // Non-fatal
        }
    }

    /// Build a plain-text report for sharing.
    func buildReportText() -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM d, yyyy h:mm a"
        let timestamp = dateFormatter.string(from: Date())

        var text = """
        ALPHADESK PORTFOLIO REPORT
        Generated: \(timestamp)
        ========================================

        ACCOUNT SUMMARY
        ----------------------------------------
        Equity:          \(formatCurrency(equity))
        Cash:            \(formatCurrency(cash))
        Buying Power:    \(formatCurrency(buyingPower))
        Unrealized P&L:  \(formatCurrency(unrealizedPnl)) (\(String(format: "%.2f", unrealizedPnlPct))%)
        Realized Today:  \(formatCurrency(realizedPnlToday))

        """

        if !positions.isEmpty {
            text += """

            CURRENT POSITIONS (\(positions.count))
            ----------------------------------------

            """
            for p in positions {
                let pnlStr = formatCurrency(p.unrealizedPnl)
                let pctStr = String(format: "%.2f%%", p.unrealizedPnlPct)
                text += """
                \(p.symbol)  |  \(Int(p.quantity)) shares  |  Avg: \(formatCurrency(p.avgCost))  |  Current: \(formatCurrency(p.currentPrice))  |  P&L: \(pnlStr) (\(pctStr))

                """
            }
        }

        if !filledOrders.isEmpty {
            text += """

            RECENT TRADES (\(filledOrders.count))
            ----------------------------------------

            """
            for o in filledOrders.prefix(20) {
                let qty = o.qty ?? "--"
                let price = o.filledAvgPrice ?? "--"
                let date = o.submittedAt ?? o.createdAt ?? "--"
                text += "\(o.symbol)  |  \(o.side.uppercased())  |  \(qty) shares @ $\(price)  |  \(date.prefix(10))\n"
            }
        }

        text += "\n========================================\nGenerated by AlphaDesk iOS"
        return text
    }

    private func formatCurrency(_ value: Double) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.currencyCode = "USD"
        formatter.maximumFractionDigits = 2
        return formatter.string(from: NSNumber(value: value)) ?? "$\(String(format: "%.2f", value))"
    }
}

// MARK: - View

struct ReportsView: View {

    @State private var vm = ReportsViewModel()
    @State private var showShareSheet = false
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ZStack {
                AD.background.ignoresSafeArea()

                if vm.isLoading {
                    LoadingView()
                        .transition(.opacity)
                } else if let error = vm.error, vm.positions.isEmpty {
                    errorView(error)
                        .transition(.opacity)
                } else {
                    reportContent
                        .transition(.opacity)
                }
            }
            .navigationTitle("Portfolio Report")
            .navigationBarTitleDisplayMode(.large)
            .toolbarBackground(AD.background, for: .navigationBar)
            .toolbarColorScheme(.dark, for: .navigationBar)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .font(.system(size: 22))
                            .foregroundStyle(AD.textTertiary)
                    }
                }
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        showShareSheet = true
                    } label: {
                        Image(systemName: "square.and.arrow.up")
                            .font(.system(size: 16))
                            .foregroundStyle(AD.accent)
                    }
                }
            }
            .animation(.easeInOut, value: vm.isLoading)
            .task { await vm.refresh() }
            .sheet(isPresented: $showShareSheet) {
                ShareSheet(items: [vm.buildReportText()])
                    .presentationDetents([.medium, .large])
            }
        }
    }

    // MARK: - Report Content

    private var reportContent: some View {
        ScrollView(.vertical, showsIndicators: false) {
            VStack(spacing: AD.spacingLG) {
                accountSummarySection
                pnlBreakdownSection
                if !vm.positions.isEmpty {
                    positionsSection
                }
                if !vm.filledOrders.isEmpty {
                    closedTradesSection
                }
                shareButton
            }
            .padding(.horizontal, AD.spacingMD)
            .padding(.top, AD.spacingSM)
            .padding(.bottom, 100)
        }
        .refreshable { await vm.refresh() }
    }

    // MARK: - Account Summary

    private var accountSummarySection: some View {
        VStack(alignment: .leading, spacing: AD.spacingSM) {
            sectionHeader("Account Summary", icon: "banknote")

            VStack(spacing: AD.spacingSM) {
                summaryRow("Total Equity", value: vm.equity, isCurrency: true)
                Divider().background(AD.border)
                summaryRow("Cash", value: vm.cash, isCurrency: true)
                Divider().background(AD.border)
                summaryRow("Buying Power", value: vm.buyingPower, isCurrency: true)
                Divider().background(AD.border)
                summaryRow("Positions Value", value: vm.totalPositionValue, isCurrency: true)
            }
            .cardStyle()
        }
    }

    private func summaryRow(_ label: String, value: Double, isCurrency: Bool) -> some View {
        HStack {
            Text(label)
                .font(.system(size: 14, weight: .medium))
                .foregroundStyle(AD.textSecondary)
            Spacer()
            if isCurrency {
                Text(value, format: .currency(code: "USD"))
                    .font(.system(size: 15, weight: .semibold, design: .monospaced))
                    .foregroundStyle(AD.textPrimary)
            } else {
                Text(String(format: "%.2f%%", value))
                    .font(.system(size: 15, weight: .semibold, design: .monospaced))
                    .foregroundStyle(AD.pnlColor(value))
            }
        }
    }

    // MARK: - P&L Breakdown

    private var pnlBreakdownSection: some View {
        VStack(alignment: .leading, spacing: AD.spacingSM) {
            sectionHeader("P&L Breakdown", icon: "chart.bar.fill")

            HStack(spacing: AD.spacingSM) {
                pnlCard(
                    "Unrealized P&L",
                    value: vm.unrealizedPnl,
                    percent: vm.unrealizedPnlPct,
                    icon: "arrow.up.arrow.down"
                )
                pnlCard(
                    "Realized Today",
                    value: vm.realizedPnlToday,
                    percent: vm.equity > 0 ? (vm.realizedPnlToday / vm.equity) * 100 : 0,
                    icon: "checkmark.circle"
                )
            }
        }
    }

    private func pnlCard(_ title: String, value: Double, percent: Double, icon: String) -> some View {
        VStack(alignment: .leading, spacing: AD.spacingSM) {
            HStack(spacing: 6) {
                Image(systemName: icon)
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(AD.pnlColor(value))
                Text(title)
                    .font(.system(size: 12, weight: .medium))
                    .foregroundStyle(AD.textTertiary)
            }

            Text(value, format: .currency(code: "USD"))
                .font(.system(size: 18, weight: .bold, design: .monospaced))
                .foregroundStyle(AD.pnlColor(value))

            Text("\(AD.pnlSign(percent))\(percent, specifier: "%.2f")%")
                .font(.system(size: 13, weight: .medium, design: .monospaced))
                .foregroundStyle(AD.pnlColor(value).opacity(0.8))
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .cardStyle()
    }

    // MARK: - Positions Table

    private var positionsSection: some View {
        VStack(alignment: .leading, spacing: AD.spacingSM) {
            HStack {
                sectionHeader("Current Positions", icon: "list.bullet.rectangle")
                Spacer()
                Text("\(vm.positions.count)")
                    .font(.system(size: 13, weight: .medium, design: .monospaced))
                    .foregroundStyle(AD.textTertiary)
            }

            VStack(spacing: 0) {
                // Header row
                HStack {
                    Text("Symbol")
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Text("Qty")
                        .frame(width: 40, alignment: .trailing)
                    Text("Avg Cost")
                        .frame(width: 70, alignment: .trailing)
                    Text("Current")
                        .frame(width: 70, alignment: .trailing)
                    Text("P&L")
                        .frame(width: 70, alignment: .trailing)
                }
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(AD.textTertiary)
                .textCase(.uppercase)
                .tracking(0.5)
                .padding(.horizontal, AD.spacingMD)
                .padding(.vertical, AD.spacingSM)

                Divider().background(AD.border)

                ForEach(vm.positions) { position in
                    positionTableRow(position)
                    if position.id != vm.positions.last?.id {
                        Divider().background(AD.border).padding(.leading, AD.spacingMD)
                    }
                }
            }
            .cardStyle(padding: 0)
        }
    }

    private func positionTableRow(_ position: Position) -> some View {
        HStack {
            HStack(spacing: 6) {
                ZStack {
                    RoundedRectangle(cornerRadius: 4, style: .continuous)
                        .fill(AD.surfaceElevated)
                        .frame(width: 28, height: 28)
                    Text(String(position.symbol.prefix(2)))
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundStyle(AD.accent)
                }
                Text(position.symbol)
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(AD.textPrimary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            Text("\(Int(position.quantity))")
                .font(.system(size: 12, weight: .medium, design: .monospaced))
                .foregroundStyle(AD.textSecondary)
                .frame(width: 40, alignment: .trailing)

            Text(position.avgCost, format: .currency(code: "USD"))
                .font(.system(size: 11, weight: .medium, design: .monospaced))
                .foregroundStyle(AD.textSecondary)
                .frame(width: 70, alignment: .trailing)

            Text(position.currentPrice, format: .currency(code: "USD"))
                .font(.system(size: 11, weight: .medium, design: .monospaced))
                .foregroundStyle(AD.textPrimary)
                .frame(width: 70, alignment: .trailing)

            VStack(alignment: .trailing, spacing: 1) {
                Text(position.unrealizedPnl, format: .currency(code: "USD"))
                    .font(.system(size: 11, weight: .semibold, design: .monospaced))
                    .foregroundStyle(AD.pnlColor(position.unrealizedPnl))
                Text("\(AD.pnlSign(position.unrealizedPnlPct))\(position.unrealizedPnlPct, specifier: "%.1f")%")
                    .font(.system(size: 9, weight: .medium, design: .monospaced))
                    .foregroundStyle(AD.pnlColor(position.unrealizedPnl).opacity(0.8))
            }
            .frame(width: 70, alignment: .trailing)
        }
        .padding(.horizontal, AD.spacingMD)
        .padding(.vertical, 10)
    }

    // MARK: - Closed Trades

    private var closedTradesSection: some View {
        VStack(alignment: .leading, spacing: AD.spacingSM) {
            HStack {
                sectionHeader("Recent Trades", icon: "clock.arrow.circlepath")
                Spacer()
                Text("\(vm.filledOrders.count)")
                    .font(.system(size: 13, weight: .medium, design: .monospaced))
                    .foregroundStyle(AD.textTertiary)
            }

            VStack(spacing: 0) {
                // Header row
                HStack {
                    Text("Symbol")
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Text("Side")
                        .frame(width: 45, alignment: .center)
                    Text("Qty")
                        .frame(width: 40, alignment: .trailing)
                    Text("Price")
                        .frame(width: 70, alignment: .trailing)
                    Text("Date")
                        .frame(width: 70, alignment: .trailing)
                }
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(AD.textTertiary)
                .textCase(.uppercase)
                .tracking(0.5)
                .padding(.horizontal, AD.spacingMD)
                .padding(.vertical, AD.spacingSM)

                Divider().background(AD.border)

                ForEach(vm.filledOrders.prefix(20)) { order in
                    tradeTableRow(order)
                    if order.id != vm.filledOrders.prefix(20).last?.id {
                        Divider().background(AD.border).padding(.leading, AD.spacingMD)
                    }
                }
            }
            .cardStyle(padding: 0)
        }
    }

    private func tradeTableRow(_ order: Order) -> some View {
        let isBuy = order.side.lowercased() == "buy"
        let sideColor = isBuy ? AD.profit : AD.loss

        return HStack {
            Text(order.symbol)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(AD.textPrimary)
                .frame(maxWidth: .infinity, alignment: .leading)

            Text(order.side.uppercased())
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(sideColor)
                .padding(.horizontal, 6)
                .padding(.vertical, 2)
                .background(sideColor.opacity(0.12))
                .clipShape(Capsule())
                .frame(width: 45, alignment: .center)

            Text(order.qty ?? "--")
                .font(.system(size: 12, weight: .medium, design: .monospaced))
                .foregroundStyle(AD.textSecondary)
                .frame(width: 40, alignment: .trailing)

            Group {
                if let price = order.filledAvgPrice, !price.isEmpty {
                    Text("$\(price)")
                } else {
                    Text("--")
                }
            }
            .font(.system(size: 11, weight: .medium, design: .monospaced))
            .foregroundStyle(AD.textPrimary)
            .frame(width: 70, alignment: .trailing)

            Text(formatShortDate(order.submittedAt ?? order.createdAt))
                .font(.system(size: 10, weight: .regular))
                .foregroundStyle(AD.textTertiary)
                .frame(width: 70, alignment: .trailing)
        }
        .padding(.horizontal, AD.spacingMD)
        .padding(.vertical, 10)
    }

    // MARK: - Share Button

    private var shareButton: some View {
        Button {
            showShareSheet = true
        } label: {
            HStack(spacing: AD.spacingSM) {
                Image(systemName: "square.and.arrow.up")
                    .font(.system(size: 16, weight: .medium))
                Text("Share Report")
                    .font(.system(size: 16, weight: .semibold))
            }
            .foregroundStyle(.white)
            .frame(maxWidth: .infinity)
            .frame(height: 52)
            .background(
                LinearGradient(
                    colors: [AD.accent, Color(hex: "3D7AE8")],
                    startPoint: .leading,
                    endPoint: .trailing
                )
            )
            .clipShape(RoundedRectangle(cornerRadius: AD.radiusMD, style: .continuous))
            .shadow(color: AD.accent.opacity(0.25), radius: 12, y: 6)
        }
    }

    // MARK: - Error View

    private func errorView(_ message: String) -> some View {
        VStack(spacing: AD.spacingMD) {
            Spacer()
            Image(systemName: "exclamationmark.triangle")
                .font(.system(size: 40))
                .foregroundStyle(AD.loss)
            Text("Failed to load report")
                .font(.system(size: 18, weight: .semibold))
                .foregroundStyle(AD.textPrimary)
            Text(message)
                .font(.system(size: 14))
                .foregroundStyle(AD.textSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, AD.spacingXL)
            Button {
                Task { await vm.refresh() }
            } label: {
                Text("Retry")
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundStyle(.white)
                    .padding(.horizontal, AD.spacingXL)
                    .padding(.vertical, 12)
                    .background(AD.accent)
                    .clipShape(Capsule())
            }
            Spacer()
        }
    }

    // MARK: - Helpers

    private func sectionHeader(_ title: String, icon: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: icon)
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(AD.textTertiary)
            Text(title)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(AD.textTertiary)
                .textCase(.uppercase)
                .tracking(0.8)
        }
    }

    private func formatShortDate(_ dateString: String?) -> String {
        guard let dateString else { return "--" }
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        var date = iso.date(from: dateString)
        if date == nil {
            iso.formatOptions = [.withInternetDateTime]
            date = iso.date(from: dateString)
        }
        if date == nil {
            let simple = DateFormatter()
            simple.locale = Locale(identifier: "en_US_POSIX")
            simple.dateFormat = "yyyy-MM-dd HH:mm:ss"
            simple.timeZone = TimeZone(abbreviation: "UTC")
            date = simple.date(from: dateString)
        }
        guard let parsed = date else { return String(dateString.prefix(10)) }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMM d"
        return formatter.string(from: parsed)
    }
}

// MARK: - Share Sheet (UIActivityViewController wrapper)

struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
